package org.firstinspires.ftc.teamcode;

public enum RobotAction {
    ALIGN_SLIDE_FOR_POINTS,
    ALIGN_SLIDE_FOR_WALL,
    EXCHANGE_SAMPLE,
    GET_SPECIMEN_FROM_WALL,
    IDLE,
    POSITION_CLAW_FOR_EXCHANGE,
    RUN_END_GAME_MODE,
    RUN_HANG_SPECIMEN,
    RUN_MANUAL_MODE,
    RUN_RELEASE_SAMPLE,
    RUN_SLIDE_RECALIBRATION,
    USE_INTAKE

}
