package org.firstinspires.ftc.teamcode;

public enum RobotAction {
    IDLE,
    USE_INTAKE,
    EXCHANGE_FROM_INTAKE,
    RUN_VERT_SLIDE_MANUALLY,
    GET_SPECIMEN_FROM_WALL,
    HANG_SPECIMEN_ON_LOW_CHAMBER,
    HANG_SPECIMEN_ON_HIGH_CHAMBER,
    PLACE_SAMPLE_IN_LOW_BUCKET,
    PLACE_SAMPLE_IN_HIGH_BUCKET,
    CLIMB_LOW_RUNG,
    CLIMB_HIGH_RUNG
}
